export default [
  {
    url: 'https://theorderguys.com',
    displayUrl: 'theorderguys.com',
    title: 'The Order Guys ',
    description: 'Online Ordering For Restaurants',
  },
  {
    url: 'https://dresscodeafrica.netlify.app/',
    displayUrl: 'dresscodeafrica',
    title: 'Dress Code',
    description: 'African Ecommerce Store',
  },
  {
    url: 'https://tacofinity.com/',
    displayUrl: 'tacofinity.com',
    title: 'Tacofinity',
    description: 'Mexican Tacqueria',
  },
  {
    url: 'https://vonssteakhouse.com/menu/',
    displayUrl: 'vonssteakhouse.com',
    title: 'Vons Steak House',
    description: 'Vons Steak House',
  },
  {
    url: 'https://neweverest.ca',
    displayUrl: 'neweverest.ca',
    title: 'New Everest Restaurant',
    description: 'New Everest',
  },
  {
    url: 'https://crystalglass.ca',
    displayUrl: 'crystalglass.ca',
    title: 'Crystal Glass',
    description: 'Crystal Glass',
  },
  {
    url: 'https://nursenextdooredm.com',
    displayUrl: 'https://nursenextdooredm.com',
    title: 'Nurse Next Door Edmonton',
    description: 'Nurse Next Door',
  },
  {
    url: 'https://www.contactinstruments.com',
    displayUrl: 'contactinstruments.com',
    title: 'Contact Instruments',
    description: 'Contact Instruments',
  },
  {
    url: 'https://www.soul2sole.com',
    displayUrl: 'soul2sole.com',
    title: 'Soul 2 Sole Massage',
    description: 'Soul2Sole',
  },
  {
    url:
      'https://www.amazon.ca/Porch-Pirate-Chest-Collapsible-Permanently/dp/B07KQJ2GXN',
    displayUrl: 'porchpiratechest',
    title: 'Porch Pirate Chest',
    description: 'Porch Pirate',
  },
  {
    url: 'https://sizzleplatter.com',
    displayUrl: 'SizzlePlatter',
    title: 'SizzlePlatter',
    description: 'SizzlePlatter',
  },
  {
    url: 'http://www.aj-drivingschool.com/',
    displayUrl: 'aj-drivingschool.com',
    title: 'A & J Driving School',
    description: 'A & Driving School',
  },
  {
    url: 'https://www.newimagecosmetic.com',
    displayUrl: 'newimagecosmetic',
    title: 'New Image Cosmetic',
    description: 'New Image Cosmetic',
  },
  {
    url: 'https://www.goauto.ca',
    displayUrl: 'GoAuto.ca',
    title: 'Go Auto',
    description: 'Go Auto',
  },
  {
    url: 'https://ricebowldeluxe.com/',
    displayUrl: 'ricebowldelux.com',
    title: 'Rice Bowl Deluxe',
    description: 'Rice Bowl Deluxe',
  },

  {
    url: 'https://www.tempuraqueen.com',
    displayUrl: 'tempuraqueen.com',
    title: 'Tempura Queen',
  },
  {
    url: 'https://sumosumosushi.com',
    displayUrl: 'sumosumosushi.com',
    title: 'Sumo Sumo Sushi',
    description: 'Japanese Restaurant',
  },
  {
    url: 'https://diamondsconsultingltd.com',
    displayUrl: 'DiamondsConsultingLtd.com',
    title: 'Diamonds Consulting',
    description: 'Data Analytics Site',
  },
  {
    url: 'https://www.pregopasta.com',
    title: 'Prego Italia',
    displayUrl: 'pregopasta.com',
    description: 'Italian Cusine',
  },
  {
    url: 'https://dash-intel.com/',
    displayUrl: 'dash-intel.com',
    title: 'Dash Intel',
    description: 'Data Analytics Site',
  },
  {
    url: 'https://butchbarber.netlify.com',
    title: 'Simple Barber',
    displayUrl: 'butchbarber.netlify.com',
    description: 'Barber Shop',
  },
  {
    url: 'https://www.foodinvitecameroon.com/',
    title: 'Food Invite',
    displayUrl: 'foodinvitecameroon.com',
    description: 'Catering Business',
  },
  {
    url: 'https://www.dresscodeafrica.com/',
    title: 'Dress Code Africa',
    displayUrl: 'dresscodeafrica.com',
    description: 'The Amazon for Africa',
  },
  {
    url: 'https://khromenailbar.com',
    title: 'Nail Salon',
    displayUrl: 'khromenailbar.com',
    description: 'Nail Bar',
  },
  {
    url: 'https://www.livetreo.ca',
    title: 'LiveTreo',
    displayUrl: 'LiveTreo.ca',
    description: 'Rental Property Company',
  },
  {
    url: 'https://newbarber.ca/book-appointment',
    title: 'Barber Booking App',
    displayUrl: 'newbarber.ca/book',
    description: 'Book Your Barber',
  },
  {
    url: 'https://www.newbarber.ca',
    title: 'Barber Finder',
    displayUrl: 'newbarber.ca',
    description: 'Find Your Barber',
  },
  {
    url: 'https://www.neverlandtea.com',
    title: 'Neverland Tea',
    displayUrl: 'neverlandtea.com',
    description: 'Neverland Tea Salon in the heart of Kits',
  },
  {
    url: 'https://dept9studios.com/',
    title: 'Dept 9 Studios',
    displayUrl: 'https://dept9studios.com/',
    description: 'Music Studio',
  },
  {
    url: 'https://www.hsodoor.com',
    title: 'No Handle Doors',
    displayUrl: 'hsodoor.com',
    description: 'No Door Handles Anymore',
  },
  {
    url: 'https://theflyingwedge.com',
    title: 'The Flying Wedge Pizza',
    displayUrl: 'theflyingwedge.com',
    description: 'The Flying Wedge Pizza',
  },
  {
    url: 'https://northlinksupply.ca',
    title: 'Northlink Supply',
    displayUrl: 'northlinksupply.ca',
    description: 'Construction Company',
  },
  {
    url: 'https://khromebeautylounge.ca',
    title: 'Khrome Beauty Lounge',
    displayUrl: 'khromebeautylounge.ca',
    description: 'Beauty Salon',
  },
  {
    url: 'https://store.jesusvr.net',
    title: 'Jesus VR',
    displayUrl: 'jesusvr.net',
    description: 'Ecommerce Store',
  },
  {
    url: 'https://amazingwok.ca',
    title: 'Amazing Wok',
    displayUrl: 'amazingwok.ca',
    description: 'Chinese Restaurant',
  },
  {
    url: '',
    title: 'Smilies Village',
    displayUrl: 'Smilies Village',
    description: 'Restaurant',
  },
  {
    url: 'https://bell-island-pizza-saskatoon.theorderguys.com',
    title: 'Bell Island Pizza',
    displayUrl: 'bell-island-pizza',
    description: 'Restaurant',
  },
  {
    url: 'https://order.morinvillepizza.com',
    title: 'Morinville Pizza',
    displayUrl: 'morinvillepizza.com',
    description: 'Restaurant',
  },
  {
    url: 'https://order.pizzaparadisereddeer.com/',
    title: 'Pizza Paradise and Donair',
    displayUrl: 'pizzaparadise.com',
    description: 'Restaurant',
  },
  {
    url: 'https://winnipegcitypizza.com',
    title: 'City Pizza',
    displayUrl: 'winnipegcitypizza.com',
    description: 'Restaurant',
  },
  {
    url: 'marketbuzz.ca',
    title: 'Market Buzz',
    displayUrl: 'marketbuzz.ca',
    description: 'Cannabis',
  },
  {
    url: 'http://zuhuredmonton.com/',
    title: 'Zuhur Edmonton',
    displayUrl: 'zuhuredmonton.com/',
    description: 'Restaurant',
  },
  {
    url: 'approvedbc.com',
    title: 'Approved BC',
    displayUrl: 'approvedbc.com',
    description: 'Restaurant',
  },
  {
    url: 'goldenricebowl.ca',
    title: 'Golden Rice Bowl',
    displayUrl: 'goldenricebowl.ca',
    description: 'Restaurant',
  },
];
